name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "*.md"
      - "*.adoc"
      - "*.txt"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "*.md"
      - "*.adoc"
      - "*.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash

      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-repo-${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Build and Test with Maven
        run: ./mvnw -B verify

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
